### ISSUE TITLE
Getting error while running go get command.

### ISSUE THREAD

**Issue by aggarwalanubhav** [storj/uplink#11]
Hi, 
Using the uplink RC v1.0.3 I've created a package and uploaded it on my repo. On using the `go get` command following warning/error shows up:
`
# storj.io/common/rpc/rpcpool
go\src\storj.io\common\rpc\rpcpool\pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:
        *Conn does not implement drpc.Conn (missing Closed method)  
`
PS: I had deleted storj.io/uplink package in my system before running the command. 
But even after these, I'm able to build my project successfully. Any specific reason behind these?

**Comment by egonelbre** [comment]
What is the project link?
