### ISSUE TITLE
func (objects *ObjectIterator) Item() *Object returns nil.

### ISSUE THREAD

**Issue by aggarwalanubhav** [storj/uplink#12]
Hi,
I've written the following code in go:
```
list := project.ListObjects(ctx, bucket.Name, &cfg)
fmt.Println("Objects list:", list)
fmt.Println("Current Object", list.Item())
```

and get the following output:
```
Objects list: &{0xc0001f0f00 0xc0001b8420 {[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] influxtest04 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0] {0 0 <nil>} 2 0 {0 0 0 0 0 0} {0 0}} {uploadPath01/testdbtxt/  0 false 2 0} {uploadPath01/testdbtxt/  false false false} <nil> 0 false <nil>}
Current Object <nil>
```

I don't understand if I have one object inside the `list` then why does the Item() function return nil.
Please look into this.
Thank you.

**Comment by egonelbre** [comment]
`ListObjects` returns an iterator over the items not a list.

The usage looks like this:

```
objects := project.ListObjects(ctx, "logs", nil)
for objects.Next() {
    item := objects.Item()
    fmt.Println(item.IsPrefix, item.Key)
}
if err := objects.Err(); err != nil {
    return err
}
```

**Comment by aggarwalanubhav** [comment]
Would this work if I have a single element in the bucket?

**Comment by egonelbre** [comment]
That exact code will work for no items, 1 item and all the items.

**Comment by aggarwalanubhav** [comment]
But the Next() function returns `false` in my case and the execution never enters the loop.

**Comment by egonelbre** [comment]
What is the full code? Currently the config isn't visible.

If it never enter the loop, it means there aren't any items based on your listing options.

**Comment by aggarwalanubhav** [comment]
The following file contains the complete code:
[storj - Copy.zip](https://github.com/storj/uplink/files/4579687/storj.-.Copy.zip)

**Comment by egonelbre** [comment]
From the code I would guess that your prefix for listing isn't a prefix of the uploaded data.

**Comment by aggarwalanubhav** [comment]
[storj - Copy.zip](https://github.com/storj/uplink/files/4579738/storj.-.Copy.zip)
The above file contains the upload code as well.

**Comment by egonelbre** [comment]
Your upload path and the prefix don't seem to match. You can try listing recursively without a prefix to debug things.

Closing as this is a bug in the code.
