### ISSUE TITLE
There is no way to list or copy objects with an empty prefix

### ISSUE THREAD

**Issue by AlexeyALeonov** [storj/uplink#13]
I can create an empty prefix with `aws s3` via Tardigrade S3 Gateway:
```
$ aws s3 --profile gateway --endpoint http://localhost:7777 mb s3://test324
$ aws s3 --profile gateway --endpoint http://localhost:7777 cp ./1.txt s3://test324//prefix/
upload: ./1.txt to s3://test324//prefix/1.txt
$ aws s3 --profile gateway --endpoint http://localhost:7777 ls s3://test324
                           PRE /
$ aws s3 --profile gateway --endpoint http://localhost:7777 ls s3://test324//
                           PRE prefix/
```

However, I can't list with such empty prefix with `uplink`:
```
$ uplink ls sj://test324//
PRE /
$ uplink ls sj://test324/
PRE /
```
It's possible only with `--recursive` flag.
```
$ uplink ls --recursive sj://test324/
OBJ 2020-09-26 19:55:39          126 /prefix/1.txt
```
However, I can't remove or copy or cat such object
```
$ uplink cat sj://test324//prefix/1.txt
Error: uplink: object not found ("prefix/1.txt")
$ uplink rm sj://test324//prefix/1.txt
Deleted sj://test324//prefix/1.txt
$ uplink ls --recursive sj://test324/
OBJ 2020-09-26 19:55:39          126 /prefix/1.txt
```

But I can remove this object via gateway:
```
$ aws s3 --profile gateway --endpoint http://localhost:7777 rm s3://test324//prefix/1.txt
delete: s3://test324//prefix/1.txt
$ aws s3 --profile gateway --endpoint http://localhost:7777 ls s3://test324//
$ aws s3 --profile gateway --endpoint http://localhost:7777 ls s3://test324/
```

By the way, with legacy AWS S3 the empty prefix is valid too.
Discussion on the forum: https://forum.storj.io/t/uplink-ls-and-uplink-ls-recrusive-results-are-different/9297

**Comment by Qweder93** [comment]
I've tried same commands, using : 
Release build
Version:            v1.48.2
Build timestamp:    08 Feb 22 15:04 EET
Git commit:         ef26ffe4d27d2b4192d07358f64ed65d8913f0dc
List command are still showing 
./uplinkng ls sj://storj2/
KIND    CREATED    SIZE    KEY
PRE                        /
And rm command : 
./uplinkng rm sj://storj2//prefix/Zoom.pkg
removed sj://storj2//prefix/Zoom.pkg

**Comment by Erikvv** [comment]
So can we close the issue?
