### ISSUE TITLE
Understand why the upload refactored code is slower

### ISSUE THREAD

**Issue by iglesiasbrandon** [storj/uplink#142]
### Description: 

We have discovered that the upload code path refactored code is slower. The purpose of this ticket is to go down the rabbit hole and figure out why this might be. The outcome of this ticket should be a list of optimizations we need to make in order for the code to get closer or faster to the old speed. If we discover it's a simple change, we should go ahead and make it. 

### Dashboard:
- https://thanos.storj.rodeo/d/5bCCsabVk/uplink-upload-refactor-comparison?orgId=1&from=now-1h&to=now

### Acceptance Criteria:
- Update the default overall concurrency limit for the part/ object data stream upload
- Update the default extra piece config for long tail cancelation 
- Measure the results and post them on this ticket to ensure the new upload code path is the same speed or faster

**Comment by shaupt131** [comment]
Based on the conversation during sprint planning, it sounds this has been figured out?  What else needs to happen to close this ticket out?
