### ISSUE TITLE
Link sharing feature

### ISSUE THREAD

**Issue by mb4ndeira** [storj/uplink#151]
### A question:
The one feature that was missing when I considered implementing uplink as a web application storage solution client, as opposed to the millions of JavaScript alternatives I'm accustomed to, is file sharing. In every web or mobile client I've developed, it has been necessary to access files on my storage provider via an authorized URL by default. Since Storj offers file sharing through CLI, I assumed it would also be possible to achieve this using the uplink Go library.

Since, I am new to the community and I'm not entirely sure what your vision is for the library. However, since file sharing is the one feature not there for my use case, I am genuinely curious to know whether you have plans to implement it in the future. Thank you.

**Comment by egonelbre** [comment]
This feature is available through (`storj.io/uplink/edge`)[https://pkg.go.dev/storj.io/uplink@v1.10.0/edge]. It's not documented as well as other features, but it's possible to decipher how `uplink` cli uses it from https://github.com/storj/storj/blob/0ca7d19fc766354fe5529a3c4224060c8c488e88/cmd/uplink/cmd_share.go#L21.

Let us know if you need more detailed help.

**Comment by mb4ndeira** [comment]
> 

I'll take a look, thanks.

**Comment by mb4ndeira** [comment]
> This feature is available through [`storj.io/uplink/edge`](https://pkg.go.dev/storj.io/uplink@main/edge). It's not documented as well as other features, but it's possible to decipher how `uplink` cli uses it from https://github.com/storj/storj/blob/0ca7d19fc766354fe5529a3c4224060c8c488e88/cmd/uplink/cmd_share.go#L21.
> 
> Let us know if you need more detailed help.

Hello, I'm back here, hope you're doing well.

So, recently, I took a peek at the package you suggested and tried plugging it's funcs into a grpc server application, but I just stumbled on the edge configuration part, and it's pretty cryptic for me to figure out alone. This [doc](https://docs.storj.io/dcs/concepts/edge-services/auth-service) did not gave any insight.

https://github.com/mb4ndeira/uplink_server/blob/main/uplink_provider/uplink.go

I even tried ignoring it: 

```
var edgeConfig edge.Config

// edgeConfig.AuthServiceAddress =
// edgeConfig.CertificatePEM =

credentials, err := edgeConfig.RegisterAccess(ctx, access, &edge.RegisterAccessOptions{Public: publicAccess})
if err != nil {
	return err
}
```

But of course it gave me: "AuthServiceAddress is missing".

Appreciate any clarification I can get on this edge config thing, thank you.

**Comment by mniewrzal** [comment]
Hey, it should be enough to specif only `edgeConfig.AuthServiceAddress` as `https://auth.storjshare.io`. This is example how [Uplink CLI is using it](https://github.com/storj/storj/blob/60444d145c68ff7440b31f09e9196ae86e201cfa/cmd/uplink/cmd_share.go#L206).

**Comment by mb4ndeira** [comment]
> Hey, it should be enough to specif only `edgeConfig.AuthServiceAddress` as `https://auth.storjshare.io`. This is example how [Uplink CLI is using it](https://github.com/storj/storj/blob/60444d145c68ff7440b31f09e9196ae86e201cfa/cmd/uplink/cmd_share.go#L206).

You're right, it's enough to only specify "https://auth.storjshare.io" (with port :7777) as the auth address, thank you for the tips, I've implemented successfully here.

**Comment by CosmicPangolin** [comment]
@mniewrzal @egonelbre

I've been banging my head in disoriented confusion all day in the battle to build a simple hosted file upload w/ downloadUrl service for an app ecosystem. This would take 20 minutes with any other cloud provider. See: https://www.tigrisdata.com/, which is now the preferred Fly.io partner.

I'm having to use the S3 gateway to get a presigned URL, and in lieu of digging through your entire codebase, was about to install the Uplink CLI in my docker container and make os/exec calls to get the url that is already the core sharing mechanic on your site.

As I mentioned several weeks ago in the forums, Storj feels HORRIBLY hostile to an app developer.  These client libraries are unmaintained and badly need sincere elbow grease, the docs are a scattered and disorienting mess, and this particular API is so horribly documented the only way to find it is...a closed issue?

Please, PLEASE make DevX a priority.  You can have the best technology and still lose this market.
