### ISSUE TITLE
New upload code path is dropping satellite errors

### ISSUE THREAD

**Issue by mniewrzal** [storj/uplink#154]
While uploading objects some limits error can happen e.g. segment limit error. At the moment in such case libuplink is returning things like `context canceled` error instead of `uplink.ErrSegmentsLimitExceeded`

Acceptance Criteria:
* return correct errors while uploading object

**Comment by mniewrzal** [comment]
https://review.dev.storj.io/c/storj/uplink/+/11170

**Comment by mniewrzal** [comment]
Issue should be fixed with above fix.

**Comment by iglesiasbrandon** [comment]
i think we can close this issues since its been deployed @mniewrzal @shaupt131
