### ISSUE TITLE
Flaky test storj.io/storj/satellite/orders/orders_test.TestProjectBandwidthDailyRollups

### ISSUE THREAD

**Issue by dlamarmorgan** [storj/uplink#163]
storj.io/storj/satellite/orders/orders_test.TestProjectBandwidthDailyRollups https://build.dev.storj.tools/job/uplink-gerrit/2790/

```
--- FAIL: TestProjectBandwidthDailyRollups/Postgres (1.26s)
orders_test.go:399: 

Error Trace:	/go/pkg/mod/storj.io/storj@v1.91.0-alpha.0.20231122114748-6b1c62d7b287/satellite/orders/orders_test.go:399

Error:      	Not equal:
        	            	expected: 78336
        	            	actual  : 52224

**Comment by egonelbre** [comment]
Report the flaky tests to https://github.com/storj/storj, because these tests are from that repo. And add an appropriate label.

**Comment by dlamarmorgan** [comment]
done.
https://github.com/storj/storj/issues/6558
