### ISSUE TITLE
Wrapper for communication over Socks proxy

### ISSUE THREAD

**Issue by neo-deb** [storj/uplink#22]
Is it possible to create a simple socks proxy wrapper for sending all information over it?

**Comment by egonelbre** [comment]
@neo-deb you can provide a custom `DialContext` in [`uplink.Config`](https://pkg.go.dev/storj.io/uplink#Config) that can implement proxying.

**Comment by neo-deb** [comment]
@egonelbre thanks for your answer! Is there any example on how to do it? Honestly, I don't know the right way for it.
Right know I have a structure like this:
```
type Storj struct {
	project *uplink.Project
	access  *uplink.Access
	ctx     context.Context
}
```
I assign the return of the function OpenProject() to my Storj.project struct. As a result inside the project field I have uplink.Config struct. So, If I want to add poxy functionality, I need to create something like ProxyDialContext inside uplink.Config or I should change the existing DialContext by adding additional arguments in it?

**Comment by egonelbre** [comment]
Using It would look something like:
```
proxy := NewProxy("xyz:123")
config := &uplink.Config{
	DialTimeout: 5*time.Second,
	DialContext: proxy.DialContext,
}
project := config.OpenProject(ctx, access)
```

And your proxy method would be something like:
```
type Proxy struct { ... }

func(proxy *Proxy) DialContext(ctx context.Context, network, address string) (net.Conn, error) {
	proxyConn, err := ...
	return proxyConn, err
}
```

**Comment by neo-deb** [comment]
You are legend! Thanks a lot
