### ISSUE TITLE
Files created using Uplink are not visible in Storj GUI

### ISSUE THREAD

**Issue by sk-ismail** [storj/uplink#40]
### 1. I was trying to upload some pictures to my bucket in storj using Uplink cli. 
![Screenshot from 2021-07-26 11-14-55](https://user-images.githubusercontent.com/42185028/126939181-e5969640-1b88-4cef-a2a1-f65b2dec3175.png)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### 2. After uploading it using uplink cli is not visible in my storj GUI.

![Screenshot from 2021-07-26 11-16-13](https://user-images.githubusercontent.com/42185028/126939283-f8f7ac0c-29e7-44ef-baee-bc22731178b7.png)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------
### 3.whereas it is visible in uplink cli 

![Screenshot from 2021-07-26 11-15-28](https://user-images.githubusercontent.com/42185028/126939318-432306bb-ef83-4102-9711-6fbf3f885af9.png)

### ----Update----

when i was trying to delete that bucket using storj gui it was giving me warning that something is there in that bucket and it couldn't delete.
That means the files are there in that bucket but not visible in storj.

![Screenshot from 2021-07-26 11-34-26](https://user-images.githubusercontent.com/42185028/126940863-7c0da0ff-0c14-44d9-a6ba-a55fc6d2dcdc.png)

**Comment by ifraixedes** [comment]
Already reported in https://github.com/storj/storj/issues/4165
