### ISSUE TITLE
Compile fails

### ISSUE THREAD

**Issue by PlainBane** [storj/uplink#87]
Compiling with Go 1.17.7, uplink v1.8.0, v1.7.1, v1.7.0 - Linux Mint 20.3
Compile exits with:
```
# storj.io/uplink/private/metaclient
/home/user/go/pkg/mod/storj.io/uplink@v1.8.0/private/metaclient/client.go:830:13: undefined: pb.BatchRequestItem_PendingStreams

```

**Comment by egonelbre** [comment]
This sounds like `go.mod` does not have the exact same version of `storj.io/common` as in `storj.io/uplink`. Ensure that the version matches https://github.com/storj/uplink/blob/main/go.mod#L11

**Comment by PlainBane** [comment]
Solved it by using `go get storj.io/uplink`. Indirect dependencies issue, I guess.
