### ISSUE TITLE
Getting error in uplink internal go files while using the uplink package in a go program.

### ISSUE THREAD

**Issue by aggarwalanubhav** [storj/uplink#9]
Hi,
I've created a package storj.go that imports the package "storj.io/uplink" with the uplink version v1.0.0. The package storj is used in a file that creates an interface to transfer the contents of one platform to storj storage platform. 

When I run the build command on my main program I get the following error:

# storj.io/uplink/private/metainfo
..\storj.io\uplink\private\metainfo\client.go:361:3: cannot use partnerID (type "github.com/skyrings/skyring-common/tools/uuid".UUID) as type "storj.io/common/uuid".UUID in field value

I, then, replaced the imported package "github.com/skyrings/skyring-common/tools/uuid" by "storj.io/common/uuid" and ran the built command again and received the following error:

# storj.io/uplink
..\storj.io\uplink\upload.go:151:3: unknown field 'ContentLength' in struct literal of type pb.SerializableMeta

I don't think making changes in the internal would solve the purpose. I request you to kindly address this issue and help me sort the same.

**Comment by egonelbre** [comment]
I think for some reason it ends up importing wrong version of `storj.io/common` in your system. I'm not quite sure why. However, try deleting `storj.io/common` from your `go.mod` file.

**Comment by aggarwalanubhav** [comment]
> I think for some reason it ends up importing wrong version of `storj.io/common` in your system. I'm not quite sure why. However, try deleting `storj.io/common` from your `go.mod` file and run `go mod tidy`. Then go should end up pulling in the right version.

Actually I, initially downloaded the latest version of uplink, i.e, v1.0.3 by using go get command. 
But I had to do my work on v1..0.0-rc1. So, I downloaded the uplink folder by selecting the corresponding tag. Then I deleted the previous uplink folder with the v1.0.0-rc1 uplink folder. This might be the reason why the wrong version of storj.io/common is getting imported. 

Kindly enlighten.

**Comment by egonelbre** [comment]
Are you using GOPATH mode while developing? I think this could be the reason you are encountering problems. Different versions have different requirements for dependencies. Handling the versions manually can be really difficult.

To properly handle versions:
1. Ensure that your project is not under GOPATH folder. If you do not know what your GOPATH is, you can run `go env GOPATH` to find out. If you have your project inside GOPATH, then go won't switch on the module versioning support.
2. Run `go mod init github.com/<username>/<project>`. If your project is not on github, then use the appropriate path. If you do not have a repository with it, then you can also use something like `example.test` for testing.
3. Run `go mod tidy` to download all the right versions.

**Comment by egonelbre** [comment]
PS: After running `go mod tidy`, you can adjust things to the right version.

**Comment by aggarwalanubhav** [comment]
My project is indeed inside the GOPATH folder. 

Shall I try deleting the stroj.io folder from my system and run the command go get storj.io/uplink@vX.Y.Z to download v1.0.0-rc1?

**Comment by egonelbre** [comment]
@aggarwalanubhav move your project outside of GOPATH, and run the go mod init command from step 2. It will be easier than managing all the correct versions manually.

**Comment by aggarwalanubhav** [comment]
Do I need to move just the main file or the required packages as well? Actually, the packages created by me are to be deployed on Github so I need to have those packages inside the github.com folder that is inside the GOPATH folder.

**Comment by egonelbre** [comment]
@aggarwalanubhav you only need to move files that you have written. The dependencies will be downloaded automatically.

**Comment by aggarwalanubhav** [comment]
@egonelbre, I tried doing what you suggested. But when I run the go build command on my project I get the following error:

build _/C_/Users/gl/Downloads/folder1/project_folder/package_1: cannot find module for path _/C_/Users/gl/Downloads/folder1/project_folder/packge_1

where project_folder is the folder where I have the main file and the packages that are imported in the main file and package_1 is one of those packages.
What could be the reason for this error?

**Comment by egonelbre** [comment]
You need to create the module. The error message would suggest that you have not done step 2. `go mod init github.com/<username>/<project>` in the project folder.

**Comment by aggarwalanubhav** [comment]
I did step 2 with the following command:

`go mod init project_folder`

**Comment by egonelbre** [comment]
In that case the import should be "package_folder/package_1". Go uses absolute paths for importing packages. Relative imports can end up very problematic.

**Comment by aggarwalanubhav** [comment]
I got the following error:
`malformed module path "project_folder/package_1": missing dot in first path element`

**Comment by egonelbre** [comment]
@aggarwalanubhav can you upload your project somewhere? This sounds like you still have a vendor folder somewhere.

**Comment by egonelbre** [comment]
Also can you give the output of running `go env`?

**Comment by aggarwalanubhav** [comment]
Here's the output to go env:

`set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\gl\AppData\Local\go-build
set GOENV=C:\Users\gl\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\gl\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=c:\go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=c:\go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=C:\Users\gl\Downloads\storj-nextcloud_V1.0.0\storj-nextcloud\go.mod
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\Users\gl\AppData\Local\Temp\go-build018950722=/tmp/go-build -gno-record-gcc-switches`

**Comment by aggarwalanubhav** [comment]
> @aggarwalanubhav can you upload your project somewhere? This sounds like you still have a vendor folder somewhere.

Actually, my project is like [storj-mongodb](https://github.com/utropicmedia/storj-mongodb) connector and has the same structure and purpose. Please take that as a reference.

**Comment by egonelbre** [comment]
Just to make it clear how the project must be setup to work properly with Go. This is not really a Storj specific issue, but in general how Go modules work. 

The following things must hold:
1. There is a go.mod file with some module name (e.g. `project.test`).
2. Importing should be based on that name. For example if you wish to import package "example" in that project folder then it must be imported as `project.test/example`.
3. You should not use vendoring when using go modules.
4. You should not keep your project in GOPATH.

You can try starting from https://github.com/storj/storj/wiki/Libuplink-Walkthrough instead. That should get you a working project.

Unfortunately, at the moment, the storj-mongodb connector has bugs related to go module handling.

**Comment by aggarwalanubhav** [comment]
This issue has been resolved. I, then, tried running `go get storj.io/uplink@v1.0.0-rc.1` but I get the error:

` #storj.io/uplink
..\..\..\go\pkg\mod\storj.io\uplink@v1.0.0-rc.1\upload.go:151:3: unknown field 'ContentLength' in struct literal of type pb.SerializableMeta`

I tried to `get` a couple of other versions as well and they happened to run successfully. So, can it be taken as a bug in the very first version of uplink?

**Comment by egonelbre** [comment]
@aggarwalanubhav use the latest version of uplink rather than rc.1. After you run the project, it should have already used the correct version.

If you try to download an older version it won't update all the other dependencies to an older version.

**Comment by aggarwalanubhav** [comment]
Also, could you please brief me about RC 1.0, as in which version of uplink refers to RC 1.0?

**Comment by egonelbre** [comment]
@aggarwalanubhav I'm not quite following the question. `1.0.0-rc.1` refers to the first release candidate of the uplink library. There have been multiple releases after it https://github.com/storj/uplink/releases. At the moment you should use `v1.0.3`.

**Comment by egonelbre** [comment]
I did a quick minimal "full featured" example how to use the library: https://github.com/egonelbre/storj-notes

**Comment by aggarwalanubhav** [comment]
Thankyou @egonelbre. Would you also please tell me what does "key" refer to while calling the UploadObject and DownloadObject method?

**Comment by egonelbre** [comment]
@aggarwalanubhav it is the "object key" the thing you use to identify an object.  Since it works as a key-value store it's the "key".

**Comment by egonelbre** [comment]
I'll close this issue since it has been resolved.

**Comment by aggarwalanubhav** [comment]
> In that case the import should be "package_folder/package_1". Go uses absolute paths for importing packages. Relative imports can end up very problematic.

Hi @egonelbre ,
What would be the import path if the project is on github i,e the go mod command was run for github project like you mentioned?

**Comment by egonelbre** [comment]
It would match the github project, e.g. `github.com/username/projectname`.

**Comment by aggarwalanubhav** [comment]
Would it be like import github.com/uername/project/package ?

**Comment by egonelbre** [comment]
Yes.

**Comment by aggarwalanubhav** [comment]
Hi @aggarwalanubhav, do we need to implement macaroon in the uplink RC like it is done in other projects with previous versions of lib/uplink?

**Comment by egonelbre** [comment]
I'm not quite following the question, but the stable API is what is in https://pkg.go.dev/storj.io/uplink?tab=doc. Whether you need the sharing features, it depends on the exact use-case. If you are implementing bindings, then you should restrict yourself to only what's in the stable API as everything else may change in the future.

**Comment by aggarwalanubhav** [comment]
Hi @egonelbre , 
Using the uplink RC I've created a package and uploaded it on my repo. On using the `go get` command following warnings/errors show up:
`# storj.io/common/rpc/rpcpool
go\src\storj.io\common\rpc\rpcpool\pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:
        *Conn does not implement drpc.Conn (missing Closed method)
# storj.io/uplink/private/metainfo
go\src\storj.io\uplink\private\metainfo\client.go:361:3: cannot use partnerID (type "github.com/skyrings/skyring-common/tools/uuid".UUID) as type "storj.io/common/uuid".UUID in field value  
`
But even after these, I'm abe to build my project successfylly. Any specific reason behind these?

**Comment by egonelbre** [comment]
`go\src\storj.io\common\rpc\rpcpool\pool.go:73:5: cannot use (*Conn)(nil) (type *Conn) as type drpc.Conn in assignment:` <-- this indicates it's loading the dependency from GOPATH for some reason.

Just to be extra clear, you must not have any code in `$GOPATH/src/storj.io` - if you do then you either have configured the modules wrong, run some command in a wrong place or something else.

**Comment by aggarwalanubhav** [comment]
I do not have any explicit code in `$GOPATH/src/storj.io`. It only contains the internal files. Could it be because there is not storj.io folder prior to running the `go get` command?

**Comment by egonelbre** [comment]
Is the code there after running `go get`? If it creates that folder, then it's still the same problem.

**Comment by egonelbre** [comment]
Let's continue the discussion in https://github.com/storj/uplink/issues/11
